/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Interfaces.Servidor_Interface;
import java.awt.GridLayout;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adson
 */
public class Mesa_Telas_Cardapio extends javax.swing.JFrame {

    private Mesa_Telas_Inicio inicio;
    private static DefaultTableModel modeloBebidas;
    private static DefaultTableModel modeloPratos;
    private static JTable tBebidas;
    private static JTable tPratos;
    private Servidor_Interface servidor;

    /**
     * Creates new form Consumo
     */
    public Mesa_Telas_Cardapio(Mesa_Telas_Inicio inicio) {
        this.inicio = inicio;
        initComponents();
        inicializarAbas();
        try {
            this.servidor = (Servidor_Interface) Naming.lookup("rmi://127.0.0.1:12345/Servidor");
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void inicializarAbas() {
        String[] colunas = {"Produto", "Valor"};

        String[][] dadosBebidas = {{"cerveja", "3,57"},
        {"refrigerante", "2,50"}};

        String[][] dadosPratos = {{"Hot Dog", "6,70"},
        {"porção Fritas", "14,50"}};

        modeloBebidas = new DefaultTableModel(dadosBebidas, colunas);
        modeloPratos = new DefaultTableModel(dadosPratos, colunas);
        tBebidas = new JTable(modeloBebidas);
        tPratos = new JTable(modeloPratos);
        jTabbedPaneCardapio.add("Bebidas", tBebidas);
        jTabbedPaneCardapio.add("Pratos", tPratos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCardapio = new javax.swing.JTabbedPane();
        jButtonPedir = new javax.swing.JButton();
        jButtonTelaInicial = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPedir.setBackground(new java.awt.Color(120, 180, 125));
        jButtonPedir.setForeground(new java.awt.Color(14, 63, 80));
        jButtonPedir.setText("Pedir");
        jButtonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirActionPerformed(evt);
            }
        });

        jButtonTelaInicial.setBackground(new java.awt.Color(120, 180, 125));
        jButtonTelaInicial.setForeground(new java.awt.Color(14, 63, 80));
        jButtonTelaInicial.setText("Tela Inicial");
        jButtonTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneCardapio)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 238, Short.MAX_VALUE)
                        .addComponent(jButtonTelaInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPedir))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPedir)
                    .addComponent(jButtonTelaInicial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicialActionPerformed
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTelaInicialActionPerformed

    private void jButtonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirActionPerformed
        if (tBebidas.getSelectedRow() != -1 || tPratos.getSelectedRow() != -1) {
            String mensagem;
            String quantidade = JOptionPane.showInputDialog(null,
                    "Digite a quantidade:",
                    "Concluir Pedido",
                    JOptionPane.QUESTION_MESSAGE);
            if (tBebidas.getSelectedRow() != -1) {
                mensagem = "2#0#"
                        + tBebidas.getModel().getValueAt(tBebidas.getSelectedRow(), 0)
                        + "#"
                        + tBebidas.getModel().getValueAt(tBebidas.getSelectedRow(), 1)
                        + "#"
                        + quantidade;
            } else {
                mensagem = "2#0#"
                        + tPratos.getModel().getValueAt(tBebidas.getSelectedRow(), 0)
                        + "#"
                        + tPratos.getModel().getValueAt(tBebidas.getSelectedRow(), 1)
                        + "#"
                        + quantidade;
            }

            try {
                servidor.imprimirMensagem(quantidade);
            } catch (RemoteException ex) {
                Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Pedido Inválido.",
                    "Selecionar produto.",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonPedirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Mesa_Telas_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Mesa_Telas_Cardapio().setVisible(true);
//            }
//        });
//    }
    public void addProdudo() {
    }

    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(true);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPedir;
    private javax.swing.JButton jButtonTelaInicial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneCardapio;
    // End of variables declaration//GEN-END:variables
}
