/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Interfaces.Mesa_Interface;
import Modelos.Servidor_Modelos_Mesa;
import Modelos.Servidor_Modelos_Produto;
import Servidor.Servidor;
import java.awt.Color;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author adson
 */
public class Servidor_Tela extends javax.swing.JFrame {

    private Servidor servidor;
    private static Mesa_Interface mesaCliente;
    private static ArrayList<Servidor_Modelos_Mesa> mesas = new ArrayList<Servidor_Modelos_Mesa>();
    private static ArrayList<Servidor_Modelos_Produto> bebidas = new ArrayList<Servidor_Modelos_Produto>();
    private static ArrayList<Servidor_Modelos_Produto> pratos = new ArrayList<Servidor_Modelos_Produto>();
    /**
     * Creates new form Servidor_Tela
     */
    public Servidor_Tela() throws IOException {
        initComponents();
        servidor = new Servidor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMesas = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneServidor = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2" }));

        jScrollPane1.setViewportView(jTextPaneServidor);

        jButton1.setText("Desligar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 292, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Servidor_Tela().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Servidor_Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static void incluirMesa(String mesa){
        mesas.add(new Servidor_Modelos_Mesa(mesa));
        try {
            mesaCliente = (Mesa_Interface) Naming.lookup("rmi://127.0.0.1:" + mesa + "/Servidor");
            mesaCliente.imprimirMensagem("5#" + mesas.size());
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Servidor_Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        gravarLog("Mesa " + mesas.size() +" está ativa.", Color.black);
        
    }
    
    public static void incluirPedido(String nome, double preco, int quantidade, int mesa){
        mesas.get(mesa).addConsumo(nome, quantidade*preco);
        gravarLog("Mesa " + mesa + " pediu " + quantidade + " " + nome + "." , Color.blue);
    }
    
    public static void incluirProduto(String nome, String categoria, double preco, int quantidade){
        if(categoria.equals("bebida")){
            bebidas.add(new Servidor_Modelos_Produto(nome, categoria, preco, quantidade));
        } else {
            pratos.add(new Servidor_Modelos_Produto(nome, categoria, preco, quantidade));
        }
    }
    
    public static void gravarLog(String mensagem, Color corMensagem) {
        SimpleAttributeSet set = new SimpleAttributeSet();
        StyleConstants.setForeground(set, corMensagem);
        Document doc;
        doc = jTextPaneServidor.getStyledDocument();
        
        try {
            doc.insertString(doc.getLength(), mensagem + "\n", set);
            StyleConstants.setForeground(set, Color.BLACK);
        } catch (BadLocationException e) {
            JOptionPane.showMessageDialog(null, "Não foi possível realizar a gravação de log.\n"
                    + "Mensagem a ser inserida: " + mensagem + "\n"
                    + "Mensagem de erro: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxMesas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextPane jTextPaneServidor;
    // End of variables declaration//GEN-END:variables
}
