/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import PacotePrincipal.*;
import clienteCaixaPER.ProdutoPER;
import java.awt.GridLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adson
 */
public class Caixa_Telas_Estoque extends javax.swing.JFrame {

    private Caixa_Telas_Inicio inicio;
    private static DefaultTableModel tabelaBebidas;
    private static DefaultTableModel tabelaPratos;
    private static JTable tBebidas;
    private static JTable tPratos;
    private String acao = "novo";//Acao pode ser: "editar" ou "novo"
    /**
     * Creates new form Consumo
     */
    public Caixa_Telas_Estoque(Caixa_Telas_Inicio inicio) {
        this.inicio = inicio;

        initComponents();
        inicializarAbas();
        mostrarEstoqueNaTela("Bebida", "Coca Cola", 3.56, 75);
        mostrarEstoqueNaTela("Prato", "Cheese Burguer", 8.70, 30);
//        JComponent panelBebidas = makeTextPanel("Tudo as Bebida");
//        jTabbedPaneCardapio.addTab("Bebidas", panelBebidas);
//        JComponent panelPratos = makeTextPanel("Tudo as Comida");
//        jTabbedPaneCardapio.addTab("Pratos", panelPratos);

    }

    public void inicializarAbas() {
        String[] colunas = {"Produto", "Valor", "Quantidade"};

        String[][] dadosBebidas = {{"cerveja", "3,57", "150"},
        {"refrigerante", "2,50", "70"}};

        String[][] dadosPratos = {{"Hot Dog", "6,70", "40"},
        {"porção Fritas", "14,50", "50"}};

        tabelaBebidas = new DefaultTableModel(dadosBebidas, colunas);
        tabelaPratos = new DefaultTableModel(dadosPratos, colunas);
        tBebidas = new JTable(tabelaBebidas);
        tPratos = new JTable(tabelaPratos);
        jTabbedPaneCardapio.add("Bebidas", tBebidas);
        jTabbedPaneCardapio.add("Pratos", tPratos);
    }

    public static void mostrarEstoqueNaTela(String categoria, String nome, double preco, int quantidade) {
        if (categoria.equals("Bebida")) {
            tabelaBebidas.addRow(new String[]{nome, String.format("%.2f", preco), String.valueOf(quantidade)});
        } else {
            tabelaPratos.addRow(new String[]{nome, String.format("%.2f", preco), String.valueOf(quantidade)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCardapio = new javax.swing.JTabbedPane();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jBDeletarProduto = new javax.swing.JButton();
        jBSalvarProduto = new javax.swing.JButton();
        jBNovoProduto = new javax.swing.JButton();
        jBEditarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(30, 120, 120));
        jLabel1.setText("Nome:");

        jComboBoxCategoria.setBackground(new java.awt.Color(120, 180, 125));
        jComboBoxCategoria.setForeground(new java.awt.Color(35, 120, 120));
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bebida", "Comida", " " }));

        jLabel2.setForeground(new java.awt.Color(35, 120, 120));
        jLabel2.setText("Preço (R$):");

        jLabel3.setForeground(new java.awt.Color(35, 120, 120));
        jLabel3.setText("Quantidade:");

        jBDeletarProduto.setBackground(new java.awt.Color(120, 180, 125));
        jBDeletarProduto.setForeground(new java.awt.Color(14, 63, 80));
        jBDeletarProduto.setText("Deletar");
        jBDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarProdutoActionPerformed(evt);
            }
        });

        jBSalvarProduto.setText("Salvar");
        jBSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarProdutoActionPerformed(evt);
            }
        });

        jBNovoProduto.setText("Novo");
        jBNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoProdutoActionPerformed(evt);
            }
        });

        jBEditarProduto.setText("Editar");
        jBEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxCategoria, 0, 166, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBDeletarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jBEditarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalvarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jBNovoProduto)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDeletarProduto)
                    .addComponent(jBSalvarProduto)
                    .addComponent(jBNovoProduto)
                    .addComponent(jBEditarProduto))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarProdutoActionPerformed
        if (jTabbedPaneCardapio.getSelectedIndex() == 0) {
            if (tBebidas.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null,
                        "Selecionar produto à ser deletado.",
                        "Operação Inválida",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                tabelaBebidas.removeRow(tBebidas.getSelectedRow());
            }
        } else if (jTabbedPaneCardapio.getSelectedIndex() == 1) {
            if (tPratos.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null,
                        "Selecionar produto à ser deletado.",
                        "Operação Inválida",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                tabelaPratos.removeRow(tPratos.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jBDeletarProdutoActionPerformed

    private void jBSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarProdutoActionPerformed
        if (acao.equals("novo")){
            String nome = this.jTextFieldNome.getText();
            String categoria = this.jComboBoxCategoria.getSelectedItem().toString();
            float preco = Float.valueOf(this.jTextFieldPreco.getText());
            int quantidade = Integer.parseInt(this.jTextFieldQuantidade.getText());
            Produto produto = new Produto (nome, categoria, preco, quantidade);
            
            ProdutoPER produtoPER = new ProdutoPER();
            if (produtoPER.inserirProduto(produto)){
                mostrarEstoqueNaTela(categoria, nome, preco, quantidade);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao Salvar");
            }
        }else if (acao.equals("editar")){
            System.out.println("editar not implemented yet!");
        }
    }//GEN-LAST:event_jBSalvarProdutoActionPerformed

    private void jBNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoProdutoActionPerformed
        this.acao = "novo";
        this.jTextFieldNome.setText("");
        this.jTextFieldPreco.setText("");
        this.jTextFieldQuantidade.setText("");
    }//GEN-LAST:event_jBNovoProdutoActionPerformed

    private void jBEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEditarProdutoActionPerformed

    public void addProdudo() {
    }

    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(true);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDeletarProduto;
    private javax.swing.JButton jBEditarProduto;
    private javax.swing.JButton jBNovoProduto;
    private javax.swing.JButton jBSalvarProduto;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPaneCardapio;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
